apiVersion: v1
appVersion: "latest"
description: Tautulli integrates with Plex to provide you a feature-rich dashboard of statistics from user activity to a graphical history of streams, play count, along with configurable notifications, and more.
name: tautulli
version: 0.1.0
