type: application
apiVersion: v2
appVersion: "v2.6.6"
description: Tautulli integrates with Plex to provide you a feature-rich dashboard of statistics from user activity to a graphical history of streams, play count, along with configurable notifications, and more.
name: tautulli
version: 1.0.2
icon: https://raw.githubusercontent.com/Tautulli/Tautulli/master/data/interfaces/default/images/logo.png
sources:
  - https://github.com/Tautulli/Tautulli
  - https://hub.docker.com/r/tautulli/tautulli
keywords:
  - tautulli
  - plex
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
